config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles # , only: [:show, :index, :new, :create, :edit, :update, :destroy]
  # Next 3 lines show how to reroute to a model
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create' # or
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                                    length: { minimum: 8, maximum: 100 },
                                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    # ||= means 'if not'
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action."
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    article_id = @article.title
    @article.destroy
    flash[:notice] = "\"#{article_id}\" was deleted successfully."
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only makes changes to your own article."
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action."
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information."
      render 'new'
    end
  end
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show, :new, :create]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  def edit
  end
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully!"
      redirect_to articles_path
    end
  end
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  def destroy
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted."
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  def require_same_user
    if current_user != @user and !current_user.admin?
      redirect_to root_path
    end
  end
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-thumbnail rounded-circle mx-auto d-block")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow bg-white rounded">
      <div class="card-header font-italic">
        by <%= article.user.username if article.user %>
      </div>
      <div class="card-body">
        <%= link_to article.title, article_path(article), class: "text-success" %>
        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
        <% if article.categories.any? %>
          <p>
            Categories: <%= render article.categories %>
          </p>
        <% end %>
        <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
        <%= link_to 'Delete', article_path(article), method: :delete,
                                                    data: { confirm: "Are you sure?" },
                                                    class: "btn btn-outline-danger" %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(article.created_at) %> ago,
        edited <%= time_ago_in_words(article.updated_at) %> ago</small>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-10">

      <%= render 'shared/errors', obj: @article %>

      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-10">
            <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |cb| %>
              <div class="form-check form-check-inline">
                <%= cb.label(class: "form-check-label input_checkbox") {cb.check_box(class: "form-check-input checkbox") + cb.text} %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles ]', articles_path, class: "text-info" %>
    </div>
  </div>

</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>

<div class="container">
  <div class="row mt-4 justify-content-center">
    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
  <%= render 'article', obj: @articles %>
  <div class="row mt-4 justify-content-center">
    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
  <div class="row mb-4 justify-content-center">
    <%= link_to '[ Create a new article ]', new_article_path, class: "text-info justify-content-center" %>
  </div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow bg-white rounded">
        <div class="card-header font-italic">
          <% if @article.user %>
            <p class="mb-2">by <%= link_to @article.user.username, user_path(@article.user), class: 'mb-2 text-body' %></p>
            <%= link_to gravatar_for(@article.user), user_path(@article.user), class: 'card-img-top' %>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left">
            <%= simple_format(@article.description) %>
            <% if @article.categories.any? %>
              <p>
                Categories: <%= render @article.categories %>
              </p>
            <% end %>
          </div>
          <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
          <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to 'Delete', article_path(@article), method: :delete,
                                                        data: { confirm: "Are you sure?" },
                                                        class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-4 mb-4 justify-content-center">
    <%= link_to '[ Return to Articles ]', articles_path, class: "text-info justify-content-center" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-light"><%= link_to category.name, category_path(category) %>&nbsp;</span>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Articles</h1>

<div class="container">

  <div class="row justify-content-center">
    <div class="col-4 mt-4">

      <div class="row mt-4 justify-content-center">
        <%= will_paginate(@category, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
      </div>
      <% @categories.each do |category| %>
        <div class="list-group text-center">
          <li class="list-group-item article-title">
            <%= link_to "#{category.name}", category_path(category) %>
            <span class="badge"><%= category.articles.count %></span>
          </li>
        </div>
      <% end %>
      <div class="row mt-4 justify-content-center">
        <%= will_paginate(@category, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
      </div>

    </div>
  </div>

</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create Category</h1>

<div class="container">

  <div class="row justify-content-center">
    <div class="col-10">

      <%= render 'shared/errors', obj: @category %>

      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Name" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to home ]', root_path, class: "text-info" %>
    </div>
  </div>

</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<div class="container">
  <div class="row mt-4 justify-content-center">
    <%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
  <%= render 'articles/article', obj: @category_articles %>
  <div class="row mt-4 justify-content-center">
    <%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
  <div class="row mb-4 justify-content-center">
    <%= link_to '[ Create a new article ]', new_article_path, class: "text-info justify-content-center" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Alpha Blog", root_path, class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- used in rails below: <a class="navbar-brand" id="logo" href="#">Alpha Blog</a> -->
  <%= link_to 'Alpha Blog', root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to 'Create new article', new_article_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
          <% end %>
          <%= link_to 'View articles', articles_path, class: "dropdown-item" %>
          <!-- <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a> -->
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? and current_user.admin? %>
            <%= link_to 'Create new category', new_category_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
          <% end %>
          <%= link_to 'All Categories', categories_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <% Category.all.each do |category| %>
            <%= link_to "- #{category.name}", category_path(category), class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', users_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link" %>
      </li>
    </ul>
    <!-- Search bar and button
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
    <ul class="navbar-nav ml-auto">
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "#{current_user.username}#{" (admin)" if current_user.admin?}" %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Settings', edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Logout', logout_path, method: :delete, class: "dropdown-item" %>
            <!-- <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a> -->
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "btn btn-outline-success mr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: "btn btn-success" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="d-flex flex-column">

    <%= render 'layouts/navigation' %>

    <div id="page-content">

      <%= render 'layouts/messages' %>

      <%= yield %>

    </div>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Alpha Blog - About</h1>

<p>
  <%= link_to 'Articles', articles_path %> |
  <%= link_to 'Home', root_path %>
</p>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center">
    <h1 class="display-4">Welcome to Alpha Blog!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to 'Sign up', signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/pages/home2.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Home</title>
</head>
<body>
  <h1>Welcome to Alpha Blog</h1>

  <p>
    <%= link_to 'Articles', articles_path %> |
    <%= link_to 'About', about_path %>
  </p>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the article from being saved:</h4>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-10">

      <%= render 'shared/errors', obj: @user %>

      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Username" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :email, class: "form-control shadow rounded", placeholder: "Email" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :password, class: "form-control shadow rounded", placeholder: "Password" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Save", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to home ]', root_path, class: "text-info" %>
    </div>
  </div>

</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container">

  <div class="row mt-4 justify-content-center">
    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
  <%= @users.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow bg-white rounded profile-card" style="width: 18rem;">
        <%= link_to gravatar_for(user), user_path(user), class: 'card-img-top mt-4' %>
        <div class="card-body">
          <h5 class="card-title"><%= user.username %></h5>
          <p class="card-text"><%= pluralize(user.articles.count, "article") if user.articles %></p>
          <%= link_to 'View Profile', user_path(user), class: "btn btn-primary" %>
          <% if logged_in? and current_user.admin? %>
            <%= link_to 'Delete User', user_path(user), method: :delete,
                                                        class: "btn btn-danger",
                                                        data: { confirm: "Are you sure you want to delete the user and all of their articles?" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <div class="row mt-4 justify-content-center">
    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>

</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s Page</h1>

<div class="container">

  <div class="row justify-content-md-center">
    <div class="col-8 mt-4 mb-4">
      <%= gravatar_for @user, size: 150 %>
    </div>
  </div>
  <h4 align="center"><%= @user.username %>'s articles</h4>
  <div class="row mt-4 justify-content-center">
    <%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
  <%= render 'articles/article', obj: @user_articles %>
  <div class="row mt-4 justify-content-center">
    <%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>

</div>